name: Update Contribution Animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            contribution-animation/github-contribution-grid-snake.svg
            contribution-animation/github-contribution-grid-snake-dark.svg?palette=github-dark
            contribution-animation/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      id: cpr
      with:
        base: main
        branch: snake-animation
        branch-suffix: timestamp
        commit-message: "Update Contribution Animation"
        delete-branch: true
        draft: false
        signoff: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        title: "update contribution animation"

    # - name: merge PR
    #     env:
    #       GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    #     run: gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --merge
